name : 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Assume IAM Role
        run: |
          CREDS=$(aws sts assume-role --role-arn arn:aws:iam::853602029602:role/Local_AI --role-session-name terraform | jq -r '.Credentials')
          export AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')
          export AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')
          export AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')
          aws sts get-caller-identity
      - name: Setup Terraform latest version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
      - name: Install Aquasec tfsec for Terraform Security Scanning
        run: 
          go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
          tfsec --config-file tfsec.yml
          tfsec .
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve