name : 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          ## the following creates an ARN based on the values entered into github secrets
          role-to-assume: arn:aws:iam::853602029602:role/Local_AI
          role-session-name: Local_AI
      - name: Setup Terraform latest version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
      - name: Terraform Format
        run: terraform fmt -check
      # - name: Install Aquasec tfsec
      #   uses: tfsec/tfsec-sarif-action@v0.0.3
      #   with:
      #     tfsec_version: latest
      #   run: |
      #     go install github.com/aquasecurity/tfsec/cmd/tfsec@latest
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve