name : 'Terraform'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853602029602:role/Llama3_ai_role
          aws-region: us-east-1
      - name: Setup Terraform latest version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest
      - name: Update Go version
        run: |
          sudo rm -rf /usr/local/go
          wget https://go.dev/dl/go1.23.5.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.23.5.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
      - name: Install Aquasec tfsec
        run: 
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Terraform Scanning
        run: 
          tfsec .
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve